import XCTest
@testable import GurbaniSearchKit

/// Parity gate: asserts the Swift fidelity core produces output BYTE-IDENTICAL to the Python
/// source of truth, using the golden vectors generated by `pipeline/gen_golden_vectors.py`.
/// Zero mismatches required. This is the native analogue of reconcile.py/golden_test.py.
final class GoldenVectorTests: XCTestCase {

    /// Walk up from this source file to the repo root and locate `contract/`.
    private func contractDir() throws -> URL {
        var dir = URL(fileURLWithPath: #filePath).deletingLastPathComponent()
        for _ in 0..<12 {
            let candidate = dir.appendingPathComponent("contract")
            if FileManager.default.fileExists(atPath: candidate.appendingPathComponent("_meta.json").path) {
                return candidate
            }
            dir = dir.deletingLastPathComponent()
        }
        throw XCTSkip("contract/ not found — run `python3 pipeline/gen_golden_vectors.py` first")
    }

    private func lines(of file: String) throws -> [String] {
        let url = try contractDir().appendingPathComponent(file)
        let text = try String(contentsOf: url, encoding: .utf8)
        return text.split(separator: "\n", omittingEmptySubsequences: true).map(String.init)
    }

    // MARK: roman_norm

    private struct RNVector: Decodable { let input: String; let output: String }

    func testRomanNormParity() throws {
        let rows = try lines(of: "golden_roman_norm.ndjson")
        XCTAssertGreaterThan(rows.count, 1000, "expected a large roman_norm corpus")
        let dec = JSONDecoder()
        var mismatches: [(String, String, String)] = []
        for row in rows {
            let v = try dec.decode(RNVector.self, from: Data(row.utf8))
            let got = RomanNorm.fold(v.input)
            if got != v.output { mismatches.append((v.input, v.output, got)) }
        }
        if !mismatches.isEmpty {
            let sample = mismatches.prefix(10)
                .map { "input=\($0.0.debugDescription) want=\($0.1.debugDescription) got=\($0.2.debugDescription)" }
                .joined(separator: "\n")
            XCTFail("roman_norm mismatches: \(mismatches.count)/\(rows.count)\n\(sample)")
        }
    }

    // MARK: difflib ratio

    private struct DLVector: Decodable { let a: String; let b: String; let ratio: String }

    func testDifflibRatioParity() throws {
        let rows = try lines(of: "golden_difflib.ndjson")
        XCTAssertGreaterThan(rows.count, 10, "expected difflib vectors")
        let dec = JSONDecoder()
        var mismatches: [(String, String, Double, Double)] = []
        for row in rows {
            let v = try dec.decode(DLVector.self, from: Data(row.utf8))
            // Python repr of the double round-trips exactly to the same IEEE-754 value.
            guard let want = Double(v.ratio) else {
                XCTFail("unparsable ratio \(v.ratio)"); continue
            }
            let got = SequenceMatcher(a: v.a, b: v.b).ratio()
            if got.bitPattern != want.bitPattern { mismatches.append((v.a, v.b, want, got)) }
        }
        if !mismatches.isEmpty {
            let sample = mismatches.prefix(10)
                .map { "a=\($0.0.debugDescription) b=\($0.1.debugDescription) want=\($0.2) got=\($0.3)" }
                .joined(separator: "\n")
            XCTFail("difflib ratio mismatches: \(mismatches.count)/\(rows.count)\n\(sample)")
        }
    }
}
