#!/usr/bin/env python3
"""WCAG 2.x contrast report for docs/brand/tokens.json (stdlib only).

Same luminance formula as ios/App/Tests/Unit/ThemeContrastTests.swift. Writes
docs/brand/contrast-report.md and exits 1 if any required pair fails. The
`forbidden` pairs document uses the brand book bans; they are reported, and the
light-leg ratio must stay under `max` (proving the ban is real, not taste).
"""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOKENS = ROOT / "docs/brand/tokens.json"
OUT = ROOT / "docs/brand/contrast-report.md"
LEGS = ["light", "dark", "lightHC", "darkHC"]


def luminance(hex_):
    h = hex_.lstrip("#")
    ch = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    lin = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in ch]
    return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]


def ratio(a, b):
    hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def resolve(tokens, name):
    if "." in name:
        group, key = name.split(".", 1)
        return tokens[group][key]
    return tokens["surfaces"][name]


def main():
    tokens = json.loads(TOKENS.read_text())
    lines = ["# Contrast report", "",
             "Generated by `scripts/brand/contrast_report.py` from `tokens.json`. Do not edit by hand.", "",
             "## Required pairs", "",
             "| Foreground | On | Min | " + " | ".join(LEGS) + " | Result |", "|---|---|---|" + "---|" * len(LEGS) + "---|"]
    failed = 0
    for chk in tokens["checks"]:
        fg = resolve(tokens, chk["fg"])
        for bg_name in chk["on"]:
            bg = resolve(tokens, bg_name)
            rs = [ratio(fg[i], bg[i]) for i in range(4)]
            ok = all(r >= chk["min"] for r in rs)
            failed += not ok
            lines.append(f"| `{chk['fg']}` | `{bg_name}` | {chk['min']} | "
                         + " | ".join(f"{r:.2f}" for r in rs) + f" | {'pass' if ok else '**FAIL**'} |")
    lines += ["", "## Forbidden uses (light leg must stay below the threshold)", "",
              "| Foreground | On | Light ratio | Threshold | Why |", "|---|---|---|---|---|"]
    for ban in tokens["forbidden"]:
        fg = resolve(tokens, ban["fg"])
        for bg_name in ban["on"]:
            r = ratio(fg[0], resolve(tokens, bg_name)[0])
            if r >= ban["max"]:
                failed += 1
            lines.append(f"| `{ban['fg']}` | `{bg_name}` | {r:.2f} | < {ban['max']} | {ban['why']} |")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT.relative_to(ROOT)}; failures: {failed}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
