#!/usr/bin/env python3
"""WCAG 2.x contrast report for docs/brand/tokens.json (stdlib only).

    python3 scripts/brand/contrast_report.py            # rewrite docs/brand/contrast-report.md
    python3 scripts/brand/contrast_report.py --check    # exit 1 if the committed page differs (CI)

Same luminance formula as ios/App/Tests/Unit/ThemeContrastTests.swift. Writes
docs/brand/contrast-report.md (a wiki page, so it carries its frontmatter) and exits 1
if any required pair fails. The `forbidden` pairs document uses the brand book bans;
they are reported, and the light-leg ratio must stay under `max` (proving the ban is
real, not taste).
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
TOKENS = ROOT / "docs/brand/tokens.json"
WEB_THEME = ROOT / "frontend/src/theme.ts"
OUT = ROOT / "docs/brand/contrast-report.md"
LEGS = ["light", "dark", "lightHC", "darkHC"]
FRONTMATTER = [
    "---",
    'title: "Contrast report"',
    'description: "Generated contrast ratios for every foreground and surface pair in the brand tokens; do not edit by hand."',
    "sidebar:",
    "  order: 2",
    "---",
]


def luminance(hex_):
    h = hex_.lstrip("#")
    ch = [int(h[i:i + 2], 16) / 255 for i in (0, 2, 4)]
    lin = [c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4 for c in ch]
    return 0.2126 * lin[0] + 0.7152 * lin[1] + 0.0722 * lin[2]


def ratio(a, b):
    hi, lo = sorted((luminance(a), luminance(b)), reverse=True)
    return (hi + 0.05) / (lo + 0.05)


def resolve(tokens, name):
    if "." in name:
        group, key = name.split(".", 1)
        return tokens[group][key]
    return tokens["surfaces"][name]


def web_theme_legs():
    """Parse frontend/src/theme.ts into {'light': {...}, 'dark': {...}} of hex values.

    Read-only validation that the marketing site's token module is present and parseable; the
    WebThemeMatchesTokens gate proves it equals tokens.json. Returns {} if the file is absent.
    """
    if not WEB_THEME.exists():
        return {}
    text = WEB_THEME.read_text()
    out = {}
    for leg in ("light", "dark"):
        m = re.search(rf"{leg}:\s*\{{(.*?)\}}", text, re.S)
        if m:
            out[leg] = dict(re.findall(r'(\w+):\s*"(#[0-9A-Fa-f]{6})"', m.group(1)))
    return out


def web_theme_section():
    """Report the marketing site's gold/ink contrast pairs (informational; never fails the run)."""
    legs = web_theme_legs()
    lines = ["", "## Web theme (frontend/src/theme.ts) — informational", ""]
    if not legs:
        return lines + ["_theme.ts not found._"]
    lines += ["| Pair | Light | Dark |", "|---|---|---|"]
    checks = [
        ("accentText on paper", "accentText", "paper"),
        ("accentText on card", "accentText", "card"),
        ("ink on paper", "ink", "paper"),
        ("onAccent on accentFill", "onAccent", "accentFill"),
    ]
    for label, fg, bg in checks:
        cells = []
        for leg in ("light", "dark"):
            d = legs.get(leg, {})
            cells.append(f"{ratio(d[fg], d[bg]):.2f}" if fg in d and bg in d else "n/a")
        lines.append(f"| {label} | {cells[0]} | {cells[1]} |")
    return lines


def build():
    """The page text and the number of failing pairs."""
    tokens = json.loads(TOKENS.read_text(encoding="utf-8"))
    lines = [*FRONTMATTER, "# Contrast report", "",
             "Generated by `scripts/brand/contrast_report.py` from `tokens.json`. Do not edit by hand.", "",
             "## Required pairs", "",
             "| Foreground | On | Min | " + " | ".join(LEGS) + " | Result |", "|---|---|---|" + "---|" * len(LEGS) + "---|"]
    failed = 0
    for chk in tokens["checks"]:
        fg = resolve(tokens, chk["fg"])
        for bg_name in chk["on"]:
            bg = resolve(tokens, bg_name)
            rs = [ratio(fg[i], bg[i]) for i in range(4)]
            ok = all(r >= chk["min"] for r in rs)
            failed += not ok
            lines.append(f"| `{chk['fg']}` | `{bg_name}` | {chk['min']} | "
                         + " | ".join(f"{r:.2f}" for r in rs) + f" | {'pass' if ok else '**FAIL**'} |")
    lines += ["", "## Forbidden uses (light leg must stay below the threshold)", "",
              "| Foreground | On | Light ratio | Threshold | Why |", "|---|---|---|---|---|"]
    for ban in tokens["forbidden"]:
        fg = resolve(tokens, ban["fg"])
        for bg_name in ban["on"]:
            r = ratio(fg[0], resolve(tokens, bg_name)[0])
            if r >= ban["max"]:
                failed += 1
            lines.append(f"| `{ban['fg']}` | `{bg_name}` | {r:.2f} | < {ban['max']} | {ban['why']} |")
    lines += web_theme_section()
    return "\n".join(lines) + "\n", failed


def main(argv=None):
    argv = sys.argv[1:] if argv is None else argv
    text, failed = build()
    rel = OUT.relative_to(ROOT)
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"::error file={rel}::stale — run: python3 scripts/brand/contrast_report.py")
            return 1
        print(f"contrast_report: {rel} is current; failures: {failed}")
        return 1 if failed else 0
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {rel}; failures: {failed}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
