#!/usr/bin/env python3
"""Generate the API's Vercel functions into the web project, and prove what `vercel build` bundled.

    python3 tools/build_api_functions.py --commit SHA [--db db/sggs.sqlite] [--into frontend]
    python3 tools/build_api_functions.py --verify-output .vercel/output

Generate (before `vercel build`), under the web project's root:

    api/svc/<ctx>.py    one function per bounded context: fixes SGGS_MODULES, SGGS_DB and SGGS_COMMIT,
                        refuses to load if its slice lacks a declared table, and serves with serve.H
    api/svc/all.py      the whole API on the full database (every path no context function owns)
    _sggs/db/<ctx>.sqlite   the context's slice, cut and proven by tools/slice_db.py
    _sggs/db/all.sqlite     the pinned full database, unchanged
    _sggs/webapp/       serve.py and its modules (no tests, no static site)
    .python-version     3.12, the runtime the API image used
    pyproject.toml      the functions' own project: no dependencies (the API is stdlib only); without
                        it the Python builder would pick up the repository's tool-only pyproject.toml

Nothing here is committed (frontend/.gitignore); the routing and per-function bundles are in
frontend/vercel.json, generated by tools/gen_gateway.py. Each function sees the original request
path and query, so serve.py routes exactly as it does on any host.

Verify (after `vercel build`, before deploying): every function bundles its entry, the API code and
its own database and nothing else from the web project; and no database or API source is in the
static output (which the whole internet can download). Stdlib only.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "tools"))
from gen_gateway import DATA_DIR, FN_DIR, function_names  # noqa: E402  one source for the layout

PYTHON_VERSION = "3.12"
PYPROJECT = f'''# Generated by tools/build_api_functions.py: the API's Vercel functions (stdlib only).
[project]
name = "sggs-api-functions"
version = "0"
requires-python = ">={PYTHON_VERSION}"
dependencies = []
'''
# Files the Python builder adds to every bundle on its own.
BUILDER_FILES = (".python-version", "pyproject.toml", "uv.lock")

ENTRY = '''"""{what} (generated by tools/build_api_functions.py; do not edit)."""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
{modules}os.environ["SGGS_DB"] = os.path.join(ROOT, "{data}", "db", "{name}.sqlite")
os.environ["SGGS_COMMIT"] = "{commit}"
sys.path.insert(0, os.path.join(ROOT, "{data}", "webapp"))

import serve  # noqa: E402

# Fail closed: a function whose database lacks a table its contexts declare must not serve.
_ready = serve.readiness()
if not _ready["ready"]:
    raise RuntimeError(f"{name}: database lacks declared tables {{_ready['missing_tables']}}")


class handler(serve.H):   # Vercel finds a function by a top-level `class handler` definition
    pass
'''


def entry(name: str, commit: str) -> str:
    if name == "all":
        what, modules = "The whole SGGS API on the full database", 'os.environ.pop("SGGS_MODULES", None)\n'
    else:
        what, modules = f"The {name} service of the SGGS API", f'os.environ["SGGS_MODULES"] = "{name}"\n'
    return ENTRY.format(what=what, modules=modules, name=name, commit=commit, data=DATA_DIR)


def generate(commit: str, into: Path, db: Path) -> None:
    if len(commit) != 40 or any(c not in "0123456789abcdef" for c in commit):
        raise SystemExit("--commit must be the full 40-character source commit")
    with open(db, "rb") as f:
        if f.read(16) != b"SQLite format 3\x00":
            raise SystemExit(f"{db} is not a SQLite database (run `make dataset`)")
    fn_dir, data = into / FN_DIR, into / DATA_DIR
    for d in (fn_dir, data):
        if d.exists():
            shutil.rmtree(d)
    fn_dir.mkdir(parents=True)
    (data / "db").mkdir(parents=True)
    shutil.copytree(ROOT / "webapp", data / "webapp",
                    ignore=shutil.ignore_patterns("tests", "static", "static.bak", "_cmp", "__pycache__",
                                                  "Dockerfile", "*.md"))
    names = function_names()
    for name in names:
        out = data / "db" / f"{name}.sqlite"
        if name == "all":
            shutil.copyfile(db, out)
        else:   # the slicer proves every kept table equal to the full DB and every FTS index whole
            subprocess.run([sys.executable, str(ROOT / "tools" / "slice_db.py"), "--db", str(db),
                            "--modules", name, "--out", str(out)], check=True)
        os.chmod(out, 0o444)
        (fn_dir / f"{name}.py").write_text(entry(name, commit), encoding="utf-8")
    (into / ".python-version").write_text(PYTHON_VERSION + "\n", encoding="utf-8")
    (into / "pyproject.toml").write_text(PYPROJECT, encoding="utf-8")
    sizes = ", ".join(f"{n} {(data / 'db' / f'{n}.sqlite').stat().st_size / 1e6:.1f} MB" for n in names)
    print(f"{len(names)} API functions at {commit[:12]} in {into} ({sizes})")


def verify_output(output: Path) -> list[str]:
    """Problems with a `vercel build` output: stray files in a bundle, or API data in static."""
    problems = []
    names = function_names()
    for name in names:
        cfg = output / "functions" / FN_DIR / f"{name}.func" / ".vc-config.json"
        if not cfg.is_file():
            problems.append(f"{name}: no function in the build output ({cfg})")
            continue
        files = set(json.loads(cfg.read_text(encoding="utf-8")).get("filePathMap", {}))
        own = f"{DATA_DIR}/db/{name}.sqlite"
        if own not in files:
            problems.append(f"{name}: its database {own} is not bundled")
        for f in sorted(files):
            if f == own or f.startswith((f"{DATA_DIR}/webapp/", f"{FN_DIR}/", "_vendor/")) or f in BUILDER_FILES:
                continue
            problems.append(f"{name}: bundles {f}, which is not part of the API")
    static = output / "static"
    if static.is_dir():
        for p in static.rglob("*"):
            rel = p.relative_to(static).as_posix()
            if p.is_file() and (rel.startswith((f"{DATA_DIR}/", f"{FN_DIR}/")) or rel.endswith((".sqlite", ".py"))):
                problems.append(f"static output would publish {rel}")
    return problems


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--commit")
    ap.add_argument("--into", type=Path, default=ROOT / "frontend")
    ap.add_argument("--db", type=Path, default=ROOT / "db" / "sggs.sqlite")
    ap.add_argument("--verify-output", type=Path, metavar="DIR")
    a = ap.parse_args(argv)
    if a.verify_output:
        problems = verify_output(a.verify_output)
        for p in problems:
            print(f"::error::{p}")
        print(f"{'FAIL' if problems else 'OK'}: {len(function_names())} API functions in {a.verify_output}")
        return 1 if problems else 0
    generate(a.commit or "", a.into, a.db)
    return 0


if __name__ == "__main__":
    sys.exit(main())
