#!/usr/bin/env python3
"""Generate docs/api/routes.md — every API route, from the code that serves it.

    python3 tools/gen_route_table.py            # rewrite docs/api/routes.md
    python3 tools/gen_route_table.py --check    # exit 1 if the committed page differs (CI)

The page is read from three places that already agree with each other by test:
webapp/serve.py:ROUTES (the dispatcher: which bounded context owns each route),
webapp/serve.py:_CACHEABLE (which responses the browser and the CDN may cache) and
tools/gen_openapi.py:ROUTES (tag, summary, parameters). A route present on one side and
missing on another fails the generation, so the page can never list a route the server does
not serve. Every path is also served under /api/v1/ with strict error semantics
(serve.H._handle_v1). Stdlib only; no database needed.
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "webapp"))
sys.path.insert(0, str(ROOT / "tools"))
import serve  # noqa: E402
import gen_openapi  # noqa: E402

OUT = ROOT / "docs" / "api" / "routes.md"
HEADER = "<!-- generated by tools/gen_route_table.py from webapp/serve.py and tools/gen_openapi.py — do not edit; run the generator -->"


def _key(path: str) -> tuple[str, str | None]:
    """'/api/analytics/author' -> ('analytics', 'author'); '/api/ang/{n}' -> ('ang', None)."""
    segs = path.split("/")[2:]
    seg1 = segs[0]
    seg2 = segs[1] if len(segs) > 1 and not segs[1].startswith("{") else None
    return seg1, seg2


def _param(pm: dict) -> str:
    s = pm.get("schema", {})
    bits = []
    if "enum" in s:
        bits.append("one of " + ", ".join(f"`{v}`" for v in s["enum"]))
    if "minimum" in s or "maximum" in s:
        bits.append(f"{s.get('minimum', '…')}–{s.get('maximum', '…')}")
    if "maxLength" in s:
        bits.append(f"≤ {s['maxLength']} chars")
    if "default" in s:
        bits.append(f"default `{s['default']}`")
    kind = "path" if pm["in"] == "path" else ("required" if pm.get("required") else "optional")
    extra = f" ({'; '.join(bits)})" if bits else ""
    return f"`{pm['name']}` — {kind}{extra}"


def build() -> str:
    served = {k: v[1] for k, v in serve.ROUTES.items()}          # (seg1, seg2) -> context
    declared = {_key(p): p for p in gen_openapi.ROUTES}
    missing = sorted(set(served) - set(declared))
    extra = sorted(set(declared) - set(served))
    if missing or extra:
        raise SystemExit(f"route tables disagree — served but not declared: {missing}; declared but not served: {extra}")
    lines = [
        "---",
        'title: "API routes"',
        'description: "Every /api route the platform serves, generated from the dispatcher and the OpenAPI declarations: its bounded context, parameters, cache policy and /api/v1 twin."',
        "sidebar:",
        "  order: 1",
        "---",
        HEADER,
        "# API routes",
        "",
        f"{len(served)} routes, read from `webapp/serve.py` (`ROUTES`, `_CACHEABLE`) and `tools/gen_openapi.py`. Every",
        "route is `GET`, read-only, and also served under `/api/v1/…` with the same body and strict errors",
        "(unknown endpoint → 404; every error is `{\"error\": {\"code\", \"message\", \"request_id\"}}`). *Cacheable*",
        "means `Cache-Control: public, max-age=300, s-maxage=3600` with an `ETag` (a matching `If-None-Match`",
        "answers 304); everything else is `no-store`. The full reference with response schemas is under",
        "[API reference](reference/); this page is the map.",
        "",
        "## By bounded context",
        "",
        "| Context | Routes | Tables it opens |",
        "|---|---|---|",
    ]
    for ctx in sorted(serve.CONTEXT_TABLES):
        routes = sorted(declared[k] for k, c in served.items() if c == ctx)
        tables = ", ".join(f"`{t}`" for t in sorted(serve.CONTEXT_TABLES[ctx]))
        lines.append(f"| `{ctx}` | {' · '.join(f'`{r}`' for r in routes)} | {tables} |")
    lines += ["", "## Every route", "", "| Route | Context | What it returns | Parameters | Cache |", "|---|---|---|---|---|"]
    for path in sorted(gen_openapi.ROUTES):
        tag, summary, params, _samples, _errors = gen_openapi.ROUTES[path]
        key = _key(path)
        ctx = served[key]
        cache = "cacheable" if key[0] in serve._CACHEABLE else "no-store"
        ps = "<br>".join(_param(p) for p in params) if params else "—"
        lines.append(f"| `{path}` | `{ctx}` | {summary} | {ps} | {cache} |")
    lines += [
        "",
        "## How this page stays true",
        "",
        "`tools/gen_route_table.py --check` runs in the docs job: if a route is added to the dispatcher or to the",
        "OpenAPI declarations without regenerating this page, the build fails. The two code tables are held",
        "to each other by a unit test, and `contract/openapi.json` is regenerated from real responses",
        "(`tools/gen_openapi.py --check` in `web-ci · python`).",
        "",
    ]
    return "\n".join(lines)


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    text = build()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"::error file={OUT.relative_to(ROOT)}::stale — run: python3 tools/gen_route_table.py")
            return 1
        print(f"gen_route_table: {OUT.relative_to(ROOT)} is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
