#!/usr/bin/env python3
"""Generate docs/reference/contributors.md — the Granth's contributors, from frontend/public/contributors.json.

    python3 tools/gen_contributors.py            # rewrite the page
    python3 tools/gen_contributors.py --check    # exit 1 if the committed page differs (CI)

The roster is the public-domain chronology the website and the app show (name strings match the
corpus author column, so the API's author counts join it). Dates are widely cited approximations;
'circa' marks the most uncertain. Historical context only — never a ranking. Stdlib only.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "frontend" / "public" / "contributors.json"
OUT = ROOT / "docs" / "reference" / "contributors.md"
HEADER = "<!-- generated by tools/gen_contributors.py from frontend/public/contributors.json — do not edit; run the generator -->"
KIND = {"guru": "The Gurus", "bhagat": "The Bhagats", "bhatt": "The Bhatts", "gursikh": "Gursikhs"}


def build() -> str:
    d = json.loads(SRC.read_text(encoding="utf-8"))
    rows = d["contributors"]
    lines = [
        "---",
        'title: "The contributors to the Granth"',
        'description: "Who wrote the hymns of Sri Guru Granth Sahib Ji: the Gurus, the Bhagats, the Bhatts and the Gursikhs, with era and region — the public-domain chronology the site and the app show."',
        "sidebar:",
        "  order: 4",
        "---",
        HEADER,
        "# The contributors to the Granth",
        "",
        "The names below are exactly the `author` strings of the corpus, so `/api/analytics/author` and the",
        "[structure page](../scripture/structure.md) join to them; the [Ang explorer](../data/line-record.md) shows",
        "their lines. Dates are widely cited approximations (scholarly ranges vary, most for the Bhagats and",
        "Bhatts; *c.* marks the most uncertain). This is historical context, never a ranking, and it awaits the",
        "same scholar review as [Scripture 101](../scripture/README.md).",
        "",
    ]
    for kind, label in KIND.items():
        group = [r for r in rows if r.get("kind") == kind]
        if not group:
            continue
        group.sort(key=lambda r: ((r.get("seq") or 0), (r.get("born") or 0), r["name"]))
        lines += [f"## {label} ({len(group)})", "", "| Name in the corpus | Roman | Lived | Era | Region | Tradition |", "|---|---|---|---|---|---|"]
        for r in group:
            lived = f"{'c. ' if r.get('circa') else ''}{r.get('born') or '?'}–{r.get('died') or '?'}"
            lines.append(f"| {r['name']} | {r.get('roman') or '—'} | {lived} | {r.get('era') or '—'} | {r.get('region') or '—'} | {r.get('tradition') or '—'} |")
        lines.append("")
        for r in group:
            if r.get("blurb"):
                lines.append(f"- **{r['name']}** — {r['blurb']}")
        lines.append("")
    lines += ["Source: `frontend/public/contributors.json` (vendored by the app at each platform release). To change an", "entry, edit the JSON and run `python3 tools/gen_contributors.py`.", ""]
    return "\n".join(lines)


def main(argv=None) -> int:
    argv = sys.argv[1:] if argv is None else argv
    text = build()
    if "--check" in argv:
        if (OUT.read_text(encoding="utf-8") if OUT.exists() else "") != text:
            print(f"::error file={OUT.relative_to(ROOT)}::stale — run: python3 tools/gen_contributors.py")
            return 1
        print(f"gen_contributors: {OUT.relative_to(ROOT)} is current")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
